name: EasyChart setup

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    env:
      OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Install and build frontend
      - name: Install frontend dependencies
        working-directory: ./src/frontend
        run: |
          npm install font-picker-react@latest --legacy-peer-deps
          npm install

      - name: Build frontend
        working-directory: ./src/frontend
        run: npm run build

      # Install and test backend
      - name: Install backend dependencies
        working-directory: ./src/backend
        run: npm install

      # Run backend tests
      - name: Run backend tests
        working-directory: ./src/backend
        run: npm test
